# .github/workflows/publish.yml
name: Publish Docker image to GHCR

on:
  push:
    branches: [main]

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      run: |
        IMAGE_NAME="ghcr.io/${GITHUB_REPOSITORY,,}"
        echo "Building image: $IMAGE_NAME"
        docker build -t $IMAGE_NAME -f .gitpod.Dockerfile .
        docker push $IMAGE_NAME